name: Cross-Platform CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        toolchain: [stable, nightly]

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose
    - name: Build Release
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose

    - name: Run help command (--help)
      shell: bash
      run: |
        cargo run -- --help | grep "A detached Rust background service"

    - name: Run short help command (-h)
      shell: bash
      run: |
        cargo run -- -h | grep "A detached Rust background service"

    - name: Run version command (--version)
      shell: bash
      run: |
        cargo run -- --version | grep "detach 0.0.1"

    - name: Run short version command
      shell: bash
      run: |
        cargo run -- -V | grep "detach 0.0.1"

    - name: Test --no-detach with timeout (Unix)
      shell: bash
      run: |
        ./target/release/detach-rs --no-detach --log-file test_no_detach_timeout.log --timeout 5
        grep "Timeout reached after 5 seconds. Terminating service." test_no_detach_timeout.log
      if: runner.os != 'Windows'

    - name: Test --no-detach with command (Windows)
      shell: bash
      run: |
        ./target/release/detach-rs.exe --no-detach --log-file test_no_detach_cmd_success.log --command "echo hello"
        findstr "Executing command: \"echo hello\"" test_no_detach_cmd_success.log
        findstr "Command executed successfully." test_no_detach_cmd_success.log
      if: runner.os == 'Windows'

    - name: Test --no-detach with command (Unix)
      shell: bash
      run: |
        ./target/release/detach-rs --no-detach --log-file test_no_detach_cmd_success.log --command "echo hello"
        grep "Executing command: \"echo hello\"" test_no_detach_cmd_success.log
        grep "Command executed successfully." test_no_detach_cmd_success.log
      if: runner.os != 'Windows'

    - name: Test --no-detach with command (Windows)
      shell: bash
      run: |
        ./target/release/detach-rs.exe --no-detach --log-file test_no_detach_cmd_success.log --command "echo hello"
        findstr "Executing command: \"echo hello\"" test_no_detach_cmd_success.log
        findstr "Command executed successfully." test_no_detach_cmd_success.log
      if: runner.os == 'Windows'



