name: Cross-Platform CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        toolchain: [stable, nightly]

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose
    - name: Build Release
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose

    - name: Run command-line tests (Non-daemonizing)
      shell: bash
      run: |
        ./target/release/detach-rs --no-detach --log-file test_no_detach.log --timeout 5 & \
        sleep 7 &&
        grep "Timeout reached" test_no_detach.log
      if: runner.os != 'Windows'

    - name: Run command-line tests (Non-daemonizing)
      shell: bash
      run: |
        .\target\release\detach-rs.exe --no-detach --log-file test_no_detach.log --timeout 5 & \
        timeout /T 7 /NOBREAK >nul # Give it time to timeout
        findstr "Timeout reached" test_no_detach.log
      if: runner.os == 'Windows'

    - name: Run command-line tests (Tailing with Timeout)
      shell: bash
      run: |
        ./target/release/detach-rs --tail --log-file test_tail.log --timeout 10 & \
        sleep 12 && true # Give it time to timeout
        grep "Timeout reached" test_tail.log
      if: runner.os != 'Windows'

    - name: Run command-line tests (Tailing with Timeout)
      shell: bash
      run: |
        .\target\release\detach-rs.exe --tail --log-file test_tail.log --timeout 10
        timeout /T 12 /NOBREAK >nul # Give it time to timeout
        findstr "Timeout reached" test_tail.log
      if: runner.os == 'Windows'
